### PR TITLE
adjust make_tests.py for tensorflow 1.14 installed with pip

### PR DESCRIPTION
**Pull request by CarlPoirier**
Hi,

I needed to make these adjustments to get the script working using Tensorflow 1.14 installed with pip. What version did you use and how did you setup?

Regards,

Carl

### CODE REVIEW

**Comment by GValiente** [comment]
I don't know how to handle this issue...

> What version did you use and how did you setup?

I'm using standalone keras, installed with pip (pip install keras).
To being able to use the GPU with keras, I followed [the official installation guide](https://keras.io/#installation).

I think I could add a flag to the script to import keras or tensorflow.keras files depending on the user input, but I don't know if it is the best way to handle this issue.

What would you do?

**Comment by CarlPoirier** [comment]
What about this?

**Comment by GValiente** [comment]
Good idea!

The import line `from tensorflow import ConfigProto, Session` is common to both code paths.

Could you add it to the pull request? Thank you.

**Comment by CarlPoirier** [comment]
Good point, latest commit should be good to go.

**Comment by GValiente** [comment]
Merged! Thank you!

**Pull request merged**
